### ISSUE TITLE
[Discussion] How Version 2-21-1-3 impact this project?

### ISSUE THREAD

**Issue by fnevesgx** [open-wa/wa-automate-nodejs#1224]
Hi,

@smashah 

I have been following this project for a long time and I would like to congratulate you and the collaborators for the effort and quality of it

I Have a doubt about the version 2.21.1.3 and the feature called "Linked Devices"
https://wabetainfo.com/whatsapp-beta-for-android-2-21-1-3-whats-new/

Did you already mapped on api how it´s gonna be ? and how will impact this project? 

Theoretically, there´is no more "pending" status, since we will not be device connection dependent.

And If it works well on next api versions, will be great

Thanks for the attention

**Comment by smashah** [comment]
@fnevesgx thanks for bringing this up. I have been keeping my eyes on the development of this feature, and over the last few months have seen things implemented in WA web that would suggest this multi device thing is more of a hack than a "feature". My guess is it's going to be just one connection to the phone which will hop around to the other devices (hence all of the TIMEOUT issues that have been popping up here lately).

There's not much chance of multi device breaking this library, and I will be first on the case when it does get released and something does go wrong.

I have a method to unlock features on WA web but I need access to the beta program in order to activate beta features. I don't have any accounts on the beta program unfortunately.

**Comment by smashah** [comment]
Closing for now. Bump to continue the discussion. Thanks
