### ISSUE TITLE
Evaluation failed: ReferenceError: WAPI is not defined

### ISSUE THREAD

**Issue by ghifar1** [open-wa/wa-automate-nodejs#1265]
**Describe the bug**
im using `goto()`, `waitForSelector()`, and `click()` from `client.getPage()` for adding a new API,
but after that if im using client again its show error from `sendText()`.
`Evaluation failed: ReferenceError: WAPI is not defined
    at __puppeteer_evaluation_script__:3:33`

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(
sessionId: sessId,
 sessionDataPath: "./data_session",
 deleteSessionDataOnLogout: true
)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2100.6,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.1.15,
  BROWSER_VERSION: HeadlessChrome/88.0.4298.0
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots
![image](https://user-images.githubusercontent.com/38382464/105501963-771d0480-5cf7-11eb-9de5-10d09c9a98c5.png)

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
There is no extended support for using puppeteer APIs. You have access to them if you know how to use them but this library is not designed for you to mess around with loading different pages or creating custom APIs. If you have any specific requests for new features let me know. Otherwise please do not try to Jerry rig things onto this library then expect us to fix what you've broken. Thanks
