### ISSUE TITLE
Feature: disableNotification parameter in muteChat function

### ISSUE THREAD

**Issue by tcortega** [open-wa/wa-automate-nodejs#1335]
Any possibility of adding this parameter? That way we don't get notifications on smartphones/other devices...
https://docs.openwa.dev/classes/client.html#mutechat

**Comment by smashah** [comment]
Just checked about this. When I mute notifications from web then they are automatically muted on all other devices. I can't manually disable notifications from the mute window on the phone because they're already muted - I would have to unmute the chat from the phone then uncheck the "show notifications" box (which is already unchecked). I think this is a dead-end if you're getting notifications on your phone when the chat is already muted.

**Comment by smashah** [comment]
@tcortega closing for now. 

Please provide some screenshots of how you can control the phone app's notifications from wa web as I can't do it on my end.

Thanks
