### ISSUE TITLE
UnhandledPromiseRejectionWarning: state: TIMEOUT

### ISSUE THREAD

**Issue by MarcosDLR** [open-wa/wa-automate-nodejs#1365]
Hello good.

I have a problem with the latest version.

Timeout is being printed and connected every time I send a message and I have the following error.

https://user-images.githubusercontent.com/47016656/108266540-9c5b3200-7140-11eb-9df3-ed870e0237b2.png
![image](https://user-images.githubusercontent.com/47016656/108266593-aaa94e00-7140-11eb-8ebe-fe687edbe9a1.png)

**Comment by smashah** [comment]
There's zero way to help you with the information you've provided.

The system usually wait's until a connection is established to continue sending a message. If you're getting a lot of timeouts it is usually due to your connection or your app going to sleep.

If there's something else and you think it's because of the library/code then I will need a lot more context.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
