### ISSUE TITLE
Send gif from url become .jpg

### ISSUE THREAD

**Issue by odhier** [open-wa/wa-automate-nodejs#1375]
when i send gif image from url with `sendFileFromUrl` function its always become .jpg in chat.

i have make sure that filename parameter is .gif

**Comment by smashah** [comment]
@odhier This isn't an issue of the library. WA converts all `GIF`s to `MP4`s in the app to save space since `GIF`s are a really inefficient file format.

You have to:

1. Make sure your server has `ffmpeg` and `chrome` installed
2. Use chrome instead of the default chromium. You can do this by setting `useChrome: true` in your config
3. Use [`sendVideoAsGif`](https://docs.openwa.dev/classes/client.html#sendvideoasgif) instead of `sendFileFromUrl`


Thanks
