### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by NitinNR** [open-wa/wa-automate-nodejs#1402]
Can it support webhook where i can receive all events and mesages ? can it support multi instances ? is this use qr code to assign perticular number with the api?

**Comment by smashah** [comment]
> Can it support a webhook where I can receive all events and messages?

Yes. If you are using the CLI then you can set a webhook with the `--webhook` or `-w` flag

E.g:

```
> npx @open-wa/wa-automate -w 'http://localhost:8080/webhook'
```

or if you are using the library normally then you can use these:

https://docs.openwa.dev/classes/client.html#registerwebhook
https://docs.openwa.dev/classes/client.html#listwebhooks
https://docs.openwa.dev/classes/client.html#removewebhook

> Can it support multi instances?

Yes. But you really shouldn't be running multiple sessions on one process because if one crashes then it takes the other down also. If you want to use multiple sessions in one process, all you need to do is give them different session IDs.

https://docs.openwa.dev/pages/The%20Client/the-client/multiple-sessions.html

> Is this use QR code to assign a particular number with the API?

Yes. When you scan a qr code, a special `.data.json` file is saved in your process working directory. The name of this file corresponds to your `sessionId`. If you do not set a `sessionId` then it defaults to `session`. If you want to scan a new qr code then you have to change the `sessionId` in your config or via `--session-id` in the CLI (e.g `--session-id session-two`)

Hope that answers your questions.
