### ISSUE TITLE
addParticipant handling errors

### ISSUE THREAD

**Issue by victorsouzaleal** [open-wa/wa-automate-nodejs#1497]
**Describe the bug**
the addParticipant function does not have a good error handling, these types of errors are not returned : Group full, Participant recently left and Participant cannot be added in groups (Only contacts). And the function cannot add to the group who has never been in it before.

**Steps to Reproduce**

1. create an addParticipant function with catch block
```javascript
client.addParticipant(from, "xxxxxxxxxxx@c.us").catch((err)=>{
         console.log(err)
 })
```
2. Try to add someone to a full group
3. Try to add someone who recently left the group
4. Try to add someone who has enabled only contacts to add to groups
5. Try to add someone who has never been in the group before
6. See? No errors in catch block.

**create() code**
This is the code you use to create the client. e.g
```javascript
module.exports = options = (headless, start) => {
    const options = {
        sessionId: 'session',
        headless: headless,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        stickerServerEndpoint: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    }
    return options
}

create(options(false, start))
    .then(client => start(client))
    .catch((error) => console.log(error))
```

**Expected behavior**
addParticipant must have an error for each situation mentioned above for better error handling.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: 2.2108.8
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
  WA_AUTOMATE_VERSION: 3.9.6
  BROWSER_VERSION: Chrome/89.0.4389.90
  OS: Windows 10
}
```

**Host (please complete the following information):**
 - OS:  Windows 10

Todo:

- [ ] Group full
- [ ] Participant recently left
- [x] Participant cannot be added in groups
- [x] Already in group

**Comment by smashah** [comment]
@victorsouzaleal what exactly is the error when you try adding a person to a 'full group' and what is that limit? Apparently it can go up to 10k?

**Comment by victorsouzaleal** [comment]
> @victorsouzaleal what exactly is the error when you try adding a person to a 'full group' and what is that limit? Apparently it can go up to 10k?

Adding to a group of 257 people, when I give the command to add, a popup appears on the cell phone warning that the group is full, but the addParticipant function does not return an error.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.9.10](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.9...3.9.10) (2021-03-21)

- Release 3.9.10 [`b848ca1`](https://github.com/open-wa/wa-automate-nodejs/commit/b848ca1c97ffc0e9f1a090f505ab8be9734a92c0)
- 🚸  improved `addParticipant` error handling #1497 [`66d7276`](https://github.com/open-wa/wa-automate-nodejs/commit/66d7276e8ab33fca21997b2c58ef4306b3fb3b30)
- ✨ feat: `addParticipant` can now add multiple participants at once #1497 [`262781c`](https://github.com/open-wa/wa-automate-nodejs/commit/262781c0c77fcd790ab979ec07276d2d8393a042)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Docs!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//create changelog image
exec(`npm run docs`);
exec(`git commit -a -m 'updated docs'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
@victorsouzaleal, to be honest, I'm not that popular so don't have access to a group with that many participants so, for now, I will just forward the errored status codes so you can decide what you want to do with them. E.g:

![image](https://user-images.githubusercontent.com/5903821/111902461-7a9de500-8a35-11eb-8424-c7dd5ea33cf8.png)

You can now also send multiple participants to add, it will try to add as many as possible and return any errored participants. For example, here I added 3 numbers, one was blocked due to privacy settings, one was the host accounts own number which was ignored, and the other one was added without problems (but the error is still thrown to inform you of the ones that had issues)

![image](https://user-images.githubusercontent.com/5903821/111902521-c94b7f00-8a35-11eb-8516-d01b46c90ea0.png)


You can see the details of the error codes here:

https://github.com/open-wa/wa-automate-nodejs/blob/783cae3ce1785eb8795b248ba6f4878ddab7e9b1/src/api/model/errors.ts#L75

For now, there is:

- `409 - participant is already in group`
- `403 - cannot add participant due to their security settings`

The good thing about this method of forwarding the error is that you can let me know what error code relates to:

- Participant recently left
- Group full

Both of which I cannot reproduce for now.

Please update to the latest version and try it out.

Thanks
