### ISSUE TITLE
Can Easy API init multiple session ?

### ISSUE THREAD

**Issue by raqaelf** [open-wa/wa-automate-nodejs#1500]
i saw in npx `@open-wa/wa-automate --help` that easy api can retrieve qr with multiple session like this
`http://localhost:3000/qr?sessionId=[sessionId]`

but i dont know how can create new session.

**Comment by smashah** [comment]
hi @raqaelf the simple answer to this question is no and that's by design.

Consider the ability to run multiple sessions in one process as a convenience for testing purposes. It is not advised in production specifically because it can cause one crash to take out all of your sessions.

Best practices is to separate each session.

Thanks
