### ISSUE TITLE
how to get browserWSEndpoint or running puppeteer browser instance?

### ISSUE THREAD

**Issue by dngda** [open-wa/wa-automate-nodejs#1537]
Is there possible to get browserWSEndpoint, so that I could get browser instance via connect to scrape other website page with puppeteer without launch another puppeteer process?

**Comment by smashah** [comment]
@dngda you shouldn't be running other processes on the same puppeteer instance as the default one in the library solely because there is no support for it if it causes any issues,

You can however connect your own puppeteer instance via the browserWSEndpoint config:

https://docs.openwa.dev/interfaces/api_model_config.configobject.html#browserwsendpoint

Thanks
