### ISSUE TITLE
Hide Tag and Many other features are Already available in other "Open Sourced" Projects!

### ISSUE THREAD

**Issue by SomnathDas** [open-wa/wa-automate-nodejs#1593]
Konichiwa ᕙ( ͡◉ ͜ ʖ ͡◉)ᕗ admin-san
Neko ~ desu. So today I brought you another statement/opinion/question against our favourite **Closed-WA** API.

**The following functions/features are already available as GA in other projects:**

- Hide Tags
- Change Group Description
- Send message To non-contacts
- Sticker Decryption
- Reply with Mentions
- On contact added

and many more...

As you've never replied **properly** to the other issue which I've made a while ago, so I thought let's provide a clear and easy to read statement against 
your " **Closed-WA** " 
-ᄒᴥᄒ-

( _P.S: I had to read "How-to write super easy to comprehend statement for dummies" book in-order to write this issue . 
ヘ(￣ω￣ヘ)_ )

Now the question is:

**Why do they require a license to use in open-wa?**

**Will they be Unlicensed** 
and " **Open-sourced** "?

**Comment by smashah** [comment]
After the last time this type of issue came up, I realized that I do not owe any of the freeloaders/spammers/code thieves an explanation or a second of my time. 

I'm proud that the existence of open-wa has resulted in so much work and innovation within other libraries.

Your shallow insults aside, I'm actually impressed and respect the work you have done on `Whatsapp-Botto-Re`. If you ever decide to pick up the project again please let me know and I'll happily set you up with a 50%+ affiliate link so that you too can be paid for your work.

P.S any other GitHub projects based on open-wa are open to the same offer.
