### ISSUE TITLE
Can't send gif as gif

### ISSUE THREAD

**Issue by Gahtee** [open-wa/wa-automate-nodejs#1644]
Describe the bug
I can send a mp4 to gif using sendVideoAsGif
but i cant send a gif using sendVideoAsGif or sendFileFromUrl
it turns into a jpeg

Steps to Reproduce
```javascript
const nyancargif = "https://gizmodo.uol.com.br/wp-content/blogs.dir/8/files/2021/02/nyan-cat-1.gif"

await client.sendVideoAsGif(from, nyancargif, 'nyancat.gif', '', id)
await client.sendVideoAsGif(from, nyancargif, 'nyancat.gif', '', id)
```
![image](https://user-images.githubusercontent.com/83777687/117334750-c20af400-ae70-11eb-911f-32abe7111c79.png)

**create() code**

```javascript
const options = (start) => {
    const options = {
        sessionId: 'Myst',
        headless: true,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    }
    return options
}
```

**Expected behavior**
I expected the bot to send the file as a normal gif.. like that:
![image](https://user-images.githubusercontent.com/83777687/117335010-10b88e00-ae71-11eb-9bc0-c9b06453c00d.png)

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: 2.2117.4,
  PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.12.0,
  BROWSER_VERSION: HeadlessChrome/90.0.4430.72
}
```

**Host**
 - OS: Windows 10

Sory for my bad english :/

**Comment by smashah** [comment]
hey @Gahtee this isn't really a bug.

Whatsapp itself does not handle .gif files. Whenever you see a "gif" in WhatsApp, it's actually just an mp4 that loops and says "gif" on it. 

For example, I downloaded your gif, went to a vanilla wa web window, dragged the gif into a chat, and sent it. It was sent as a static image, just like in your example.

The reason for this is because .gif is an old and inefficient format.

I suggest grabbing mp4 links from gif sites (giphy has mp4 links for all their content) or using building out a .gif => .mp4 converter using [ffmpeg-fluent](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg)

I suggest joining the discord to discuss solutions further with community members who have also come across this.

Closing. Thanks
