### ISSUE TITLE
isChatOnline function is not working as expected

### ISSUE THREAD

**Issue by akkivirani** [open-wa/wa-automate-nodejs#1673]
I observed that isChatOnline function is not getting online/offline status for some of the chats.
If I will open that chat from my phone, it will start working.
Also Can we get online/offline status for any number even if it is not present in our chat?

Any help will be appreciated.

**Comment by smashah** [comment]
Hey there @akkivirani 

> I observed that `isChatOnline` function is not getting online/offline status for some of the chats.

Due to recent updates from WA, some things fall back to a recent value instead of continuously updating it from the phone. For this reason, you should make sure that the phone is always open, on charge, online, and in the mobile app to ensure data is as correct and recent as possible.

> Also Can we get online/offline status for any number even if it is not present in our chat?

No, it cannot. Due to recent events in the news, the zuck is going around and patching these creepy workarounds.
