### ISSUE TITLE
Docx is decyptMedia as mp4.

### ISSUE THREAD

**Issue by syafiqfaiz** [open-wa/wa-automate-nodejs#1727]
**Describe the bug**
File with a docx extension is sent properly as docx file, but when processed, its decrypted as mp4 mimeType.

**Steps to Reproduce**
1) encode to dataUrl using browse FileReader api
```
const reader = new FileReader();
reader.readAsDataURL(file);
 ```
*it encode the file as `data:application/octet-stream;`*
2) send a docx file from browser using `sendFile` api
3) list to onAnyMessage event
4) decryptMedia, now it encode the file as `data:video/mp4`

**create() code**
This is the code you use to create the client. e.g
```javascript
var wa = require('@open-wa/wa-automate');
var _config = require('./config.json');
const fs = require('fs')


var _waConfig = {
	sessionId: _config.phone,
	licenseKey: _config.license,
};

var _whatsappStart = (whatsapp) => {
	console.log('Successfully start WhatsApp Web');

	whatsapp.onStateChanged((state) => {
		console.log('onStateChanged', state);

		switch (state) {
			case 'CONFLICT':
			case 'UNLAUNCHED':
				whatsapp.forceRefocus();
				break;
			default:
				break;
		}
	});

	whatsapp.onAnyMessage((message) => {
		
		whatsapp.decryptMedia(message).then((mediaData) => {
			console.log(JSON.stringify(mediaData));
			console.log('=== END ===');
		});
	});

	fs.readFile('../file.docx', {encoding: 'base64'} , (err, data) => {
		if (err) {
			console.error(err)
			return
		}
		whatsapp.sendFile(
			'mynumber@c.us',
			'data:application/octet-stream;base64,' + data,
			'filename.docx', // filename
			'caption',
			null,
			true
		).then((msgId) => {
			console.log('sendFile', msgId);
		})
		.catch((err)=>{console.error(err)})
		;
	})
};

wa.create(_waConfig)
.then(async client => await _whatsappStart(client))
.catch(e => {
	console.log('CREATE ERROR', e.message);
});
```

**Expected behavior**
Expected a document mimeType

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION:  '2.2119.6' 
  PAGE_UA:  'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
  WA_AUTOMATE_VERSION: '3.15.2 UPDATE AVAILABLE: 4.0.2'
  BROWSER_VERSION: 'HeadlessChrome/91.0.4469.0' 
}
```

**Host (please complete the following information):**
 - OS: Andoroid

**Additional context**

**Comment by smashah** [comment]
Haha 😂

I just woke up but I will explain why this happens in a bit

**Comment by smashah** [comment]
Hi @syafiqfaiz The reason this happens is because the majority use case for unknown mimetypes is `data:application/octet-stream` and based on user feedback, `data:application/octet-stream` generally means the file is a video.

Now, is it compliant to assume that `octet-stream`s are by default a video? Absolutely not! But it is the case that many people using the library intend for the octet-stream to resolve as a video.

What is the solution for this?

Since you are explicitly setting the mime-type in your code, you should actually be using an explicit mime-type (`octet-stream` is a meaningless mime-type) that correctly identifies your file. Based on the following sources:

https://www.iana.org/assignments/media-types/media-types.xhtml
https://en.wikipedia.org/wiki/Media_type

You should be using this code for .docx files:

```javascript
...
		whatsapp.sendFile(
			'mynumber@c.us',
			'application/vnd.openxmlformats-officedocument.wordprocessingml.document;base64,' + data,
			'filename.docx', // filename
			'caption',
			null,
			true
		).then((msgId) => {
			console.log('sendFile', msgId);
		})
		.catch((err)=>{console.error(err)})
		;
	})
};
...
```

I will add a caveat in the documentation regarding this issue

**Comment by syafiqfaiz** [comment]
I am not explicitly setting the mimeType in my code
I am actually using browser API tu encode the file into dataUrl
```
const reader = new FileReader();
reader.readAsDataURL(file);
```

here's how I use it in react
```
 const onSendFile = (file) => {
    const filename = file.name;
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      dispatch(
        Actions.sendWhatsappFile({
          replyBy: { id: user.id, name: user.name || '' },
          selectedConversation,
          base64: reader.result,
          filename,
          caption: '',
        })
      );
    };
    setShowFileModal(false);
  };
  ```

and for an unknown reason, `FileReader` api decode `docx` file as `data:application/octet-stream;`

I hardcode it in the example because `fs.readFile` doesnt' encode in dataUrl, only in base64.

Do you have any suggestion on encoding the file to the correct mimeType in browser?

**Comment by smashah** [comment]
I suggest using a library like [`mime-types`](https://npm.runkit.com/mime-types) to infer the correct mimetype from a file

![image](https://user-images.githubusercontent.com/5903821/119795748-ab384a00-bed0-11eb-9c8a-75619294313a.png)

octet-stream is a placeholder for an `unknown` file type so is pretty useless for most use cases.

Due to the fact that this issue and #1725 have come up at the same time means I should just implement the above suggestion within the library itself.

TODO:

- [ ] If mime-type includes `undefined` or `octet-stream` then infer mime-type using `filename` or `file` (if `file` is filepath or URL)

**Comment by syafiqfaiz** [comment]
ok

> If mime-type includes undefined or octet-stream then infer mime-type using filename or file (if file is filepath or URL)

I should probably use the same strategy on the client side. If the mimType provided by `FileReader` is `octet-stream`, find the mimetype from the file extension.

Thank you @smashah , thank for this awesome package

**Comment by smashah** [comment]
@syafiqfaiz the library will now detect the content-type from the filename in the latest version 4.1.0


https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.1.0

thanks
