### ISSUE TITLE
Is it possible to use getAllContacts to create a broadcast list?

### ISSUE THREAD

**Issue by GladistonXD** [open-wa/wa-automate-nodejs#1753]
Using getAllContacts to leave the list in 'possible' acceptable format
```
const list = ('xxxxx@c.us', 'xxxxx@c.us' , 'xxxxx@c.us', 'xxxxx@c.us')

client.sendText(list, message)
true_xxxxx@c.us_xxxxx
true_xxxxx@c.us_xxxxx
true_xxxxx@c.us_xxxxx
true_xxxxx@c.us_xxxxx

```
would be more or less that

**Comment by smashah** [comment]
@GladistonXD This wouldn't be a built-in feature of the library because some may use it and get their accounts nuked.

To do what you're trying to achieve you could do something like this:


```
	const contacts = await client.getAllContacts();
	const message_ids = await Promise.all(contacts.map(({id})=>client.sendText(id,message)))
```

Not sure what you mean by "leave the list in 'possible' acceptable format". 

Please discuss this further on the discord. thanks

**Comment by GladistonXD** [comment]
Sorry I'm from Brazil and I use Google translator sometimes it doesn't work out as it should :) Still on the nuked, if you use a 'delay' in the promises maybe avoid the ban?

**Comment by smashah** [comment]
@GladistonXD that would be a good way to mitigate risk but i can provide no promises on what will and wont result in a ban. You can discuss this further in the discord
