### ISSUE TITLE
getAllChats functions

### ISSUE THREAD

**Issue by husseindia** [open-wa/wa-automate-nodejs#2029]
hello Dear
do you have function to get all chats from started to all contacts ??

**Comment by phaalonso** [comment]
Hi, I belive that `client.getAllChats()` do this. If there is need to restrict to these that have messages, you can use `client.getAllChatsWithMessages()`

**Comment by smashah** [comment]
https://docs.openwa.dev/classes/api_Client.Client.html#getAllChatsWithMessages

**Comment by husseindia** [comment]
this function get only 8 object of msg, how to get all msgs from chats

**Comment by smashah** [comment]
> this function get only 8 object of msg, how to get all msgs from chats

It fetches whatever messages are loaded in the session. I highly suggest not getting all messages from all chats as it WILL crash your process due to the massive amount of memory needed to keep all those messages in the session.

for each chat you will need to run https://docs.openwa.dev/classes/api_Client.Client.html#loadAllEarlierMessages
