### ISSUE TITLE
What can cause "Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed."

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2189]
What can cause this error for all methods?

{"success":false,"error":{"name":"Error","message":"Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed."}}

Doesn't have any pattern to happen. But occur all the time.

**Comment by smashah** [comment]
@silvaartur This happens because when the library requests puppeteer to execute the command, the page or browser doesn't respond or has crashed. This may happen for many different reasons - maybe check your system resources? I've seen this happen to people running on ec2 instances which are too small
