### ISSUE TITLE
session.data.json

### ISSUE THREAD

**Issue by jhonalex949** [open-wa/wa-automate-nodejs#2255]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When you of new try loggin, this error appears into session.data.json 
"Expected a JSON object, array or literal.

### Expected Behavior

previously, I started session without having to qr code scanner newly. With file session.data.json its should start session without problem, but the terminal returns qr code for logging session of new as if there was no saved the session.

### Steps To Reproduce

1.Download latest version Visual studio code.
2. Install latest version of @open-wa/wa-automate
3. Run the sample that firts example of repository
4. You scanner qr code for authenticate.
5. When you have authenticate, stop code.
6. You  run the code new for know if session saved.
7. Note that it does not save the session because it asks for the qr code again.

### Mode

EASY API/CLI

### create() code

```markdown
// import { create, Client } from '@open-wa/wa-automate';
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2142.12",
  "WA_AUTOMATE_VERSION": "4.23.6",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1635717461026
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.0
- npm: 8.1.0
```

### Screenshots

![bug](https://user-images.githubusercontent.com/24654641/139604084-c1ecc191-2aab-4a23-ae1b-4a6bf5577219.jpg)

**Comment by smashah** [comment]
This is not an error with the library, this is your vs-code linter moaning because it expects json in the `.data.json`. It used to be bare json but now the json object is encoded as base64 for portability + repeatability.

Now, as to why exactly you're not able to reauthenticate.. That's a different issue. Your `.data.json` is suspiciously short.

If you copy paste your `.data.json` into a base64 decoder. You can see that content is:

```json
{"WABrowserId":"\"djQuQJy5m3FyFMVuD1t/UQ==\""}
```

Critical re-authentication data is missing here.

This is most likely happening to you because you are attempting to sign in using multi-device mode without telling the create command that you intend to do so.

Try to change:

`wa.create().then(client => start(client));`

to 

`wa.create({multiDevice: true}).then(client => start(client));`

and then delete the `session.data.json` file. And try again.

Please note, MD is in beta so I suggest not using it.

**Comment by smashah** [comment]
Yes, I have just checked. You are getting a `WABrowserId` only `.data.json` because your WA account is in MD mode.

Either turn off MD mode (normal mode is more stable) or set `{multiDevice: true}` in the `create` command

**Comment by jhonalex949** [comment]
Hi Mohammed Shah, if indeed that is the problem. I tried as you say with `{multiDevice: true}` and sometimes it works and sometimes it doesn't, in MD  mode.  There are occasions that do not login. 
Without MD mode I don't have problem, work perfectly.
Thanks for you help.
