### ISSUE TITLE
Not recognize all conversations

### ISSUE THREAD

**Issue by chgss** [open-wa/wa-automate-nodejs#2559]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

```bash
 Client loaded for normal account with 1 contacts, 0 chats & 0 messages in 8.053s


Not a contact. Unlock this feature and support open-wa by getting a license:

12|1015-whatsapp  | - QR code scanned. Loading session...
12|1015-whatsapp  | - QR code scanned. Loading session...
12|1015-whatsapp  | - Reinjecting api
12|1015-whatsapp  | - Injecting scripts
12|1015-whatsapp  | - Base inject: 25ms
12|1015-whatsapp  | - Launch inject: 347ms
12|1015-whatsapp  | - WAPI Reinjected
12|1015-whatsapp  | - Checking if session is valid
12|1015-whatsapp  | - Downloading patches from https://cdn.openwa.dev/patches.json
12|1015-whatsapp  | - Client is ready
12|1015-whatsapp  | - Downloaded patches in 0.082s
12|1015-whatsapp  | - Installing patches
12|1015-whatsapp  | - Patches Installed: e57fa
12|1015-whatsapp  | - Client loaded for normal account with 1 contacts, 0 chats & 0 messages in 8.983s
12|1015-whatsapp  | - Finalizing web session...
12|1015-whatsapp  | - Finalizing client...
12|1015-whatsapp  | - 🚀 @OPEN-WA ready for account: 2565
12|1015-whatsapp  | - 1015_STARTUP
12|1015-whatsapp  | - Please see machine logs to see the API key
12|1015-whatsapp  | Please use the following api key for requests as a header:
12|1015-whatsapp  | api_key: 
12|1015-whatsapp  | - Setting Up API Explorer
12|1015-whatsapp  | - API Explorer set up successfully
12|1015-whatsapp  | - ...waiting for port 8016 to be free
12|1015-whatsapp  | - Port 8016 is now free.
12|1015-whatsapp  | - 
12|1015-whatsapp  | 	API Explorer (​http://localhost:8016/api-docs/ ​)
12|1015-whatsapp  | - 
12|1015-whatsapp  | • Listening on port 8016!
▄12|1015-whatsapp  | - Injecting scripts
12|1015-whatsapp  | - Base inject: 27ms
12|1015-whatsapp  | - Launch inject: 123ms
12|1015-whatsapp  | - Injecting scripts
12|1015-whatsapp  | - Base inject: 6ms
12|1015-whatsapp  | ConsoleMessage {
12|1015-whatsapp  |   _type: 'error',
12|1015-whatsapp  |   _text: 'Failed to load resource: the server responded with a status of 500 ()',
12|1015-whatsapp  |   _args: [],
12|1015-whatsapp  |   _stackTraceLocations: [
12|1015-whatsapp  |     {
12|1015-whatsapp  |       url: 'https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F188965907_398954071882033_38795729324032637_n.jpg%3Fccb%3D11-4%26oh%3De0a6dc87b36d47d6facf21512646d201%26oe%3D6232B7FD&t=s&u=%40c.us&i=1640147886&n=%2BpaeSuFqfa0psLGvg5gU3IXhur68MOquAGM2uIj9bME%3D',
12|1015-whatsapp  |       lineNumber: undefined
12|1015-whatsapp  |     }
12|1015-whatsapp  |   ]
12|1015-whatsapp  | }
12|1015-whatsapp  | ConsoleMessage {
12|1015-whatsapp  |   _type: 'error',
12|1015-whatsapp  |   _text: 'Failed to load resource: the server responded with a status of 500 ()',
12|1015-whatsapp  |   _args: [],
12|1015-whatsapp  |   _stackTraceLocations: [
12|1015-whatsapp  |     {
12|1015-whatsapp  |       url: 'https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F261652053_484540506475852_1500726667944125229_n.jpg%3Fccb%3D11-4%26oh%3D01_AVwwYG2DOLFhy78bA9dF32W9fYNaom-DsC2_SxWA0GK0Pw%26oe%3D6233C8EB&t=s&u=%40c.us&i=1647042231&n=ezfCsR0jUyIP0%2B1oLiDxl2dmtuq%2BxKsK%2BvhQzzB7URw%3D',
12|1015-whatsapp  |       lineNumber: undefined
12|1015-whatsapp  |     }
12|1015-whatsapp  |   ]
12|1015-whatsapp  | }
12|1015-whatsapp  | - Launch inject: 122ms
12|1015-whatsapp  | ConsoleMessage {
12|1015-whatsapp  |   _type: 'info',
12|1015-whatsapp  |   _text: `Clear-Site-Data header on 'https://web.whatsapp.com/?post_logout=1': Cleared data types: "storage".`,
12|1015-whatsapp  |   _args: [],
12|1015-whatsapp  |   _stackTraceLocations: [ { url: 'https://web.whatsapp.com/', lineNumber: undefined } ]
12|1015-whatsapp  | }
12|1015-whatsapp  | LOGGED OUT
12|1015-whatsapp  | Session most likely logged out
12|1015-whatsapp  | !!!! CLIENT LOGGED OUT !!!!
12|1015-whatsapp  | Shutting down.
12|1015-whatsapp  | - 1015_STARTUP
```

**** CONFIG

```js
{
        "useChrome":true,
        "logConsole":true,
        "webhook":
        [
                {
                "url":"https://domin.com/wap/?service=owa",
                "events":"all"
                }
        ],
        "sessionId":"1015",
        "sessionDataPat5":"/root/owa/session/1015/",
        "port":8016,
        "key":"xxxxxx",
        "pQueueDefault":{
                "intervalCap":1,
                "interval":2000,
                "carryoverConcurrencyCount":true
        },
        "customUserAgent":"Mozilla / 5.0 (compatible; MSIE 10.0; Windows; Windows NT 10.3;; en-US Trident"
}
```

### Steps To Reproduce

1. Normal steps
2. start with pm2
3. 

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2208.7",
  "WA_AUTOMATE_VERSION": "4.32.5",
  "BROWSER_VERSION": "HeadlessChrome/95.0.4638.69",
  "START_TS": 1647102332369,
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 4.18
- Node: 14.17.3
- npm: 8.1.2
```

**Comment by linconrezende** [comment]
Yes, this happens everytime we delete all conversations. Whatsapp web beta stop seeing all chats.
I realized it only happens on the new BETA version.
OpenWA free dont send messages to those "hidden" chats, because it thinks it is not from our contact list. But it is.
The only way of getting conversations back, is to send a message from the phone to all those chats, so they become visible again to OpenWA.

**Comment by linconrezende** [comment]
It also happens when we try to load the conversations BEFORE the API is injected.
Ive searched for hours, and **there is NO secure way of knowing if the client is REALY READY or not**.

(this is the best tricky way I've come up with)
So I put a await for 20 after the client says it is ready, because it is nevery ready. I takes at least 10 seconds (it is random).

Another way of trying to get it right, is to wait the **client.onStateChanged** for **CONNECTED** and only then try to use the function **client.getMe()** and then check if **me.isContactSyncCompleted** is true, but again, this doesn't work every time, because not every time the client sync the contacts. So it will be false even if the client is ready.
AND, the onStateChanged event doesn't work every time. Some times, randomly, it never initilizes and never fires my custom onStateChage function.

Another way is to do a **client.healthCheck()** before getting all chats, but AGAIN, it doesn't work every single time.

For those specific reasons, OpenWA is the BEST and the most UNSTABLE library I've seen so far.
It coult be because of my implementation? sure ;)

**Comment by smashah** [comment]
@linconrezende the latest version has `"waitForRipeSession:true" by default. Also, @chgss managed to fix this issue by updating the app on the phone.

**Comment by linconrezende** [comment]
@smashah thank you but.. I doesn`t change anything.

// wait for a valid headful session. Not required in recent versions.
waitForRipeSession:true

what does even means? We need a callback when the API and the OpenWA API is finished injecting everything and the whole client is TRULLY ready to use.
Or only returns the client on the create when we can actually use it..
I'm always on the latest versions of everything I can. Sometimes whatsapp won't let me update because of the country but I manage to the the apk file anyways.

**Comment by smashah** [comment]
@linconrezende please file a new issue using the template with all context.
