### ISSUE TITLE
Store a session in S3Bucket with multidevice enabled

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#2768]
How can i store a session in a S3 Bucket with the multidevice enabled as it generate an "_IGNORE_SESSION" folder and no longer a "session.data.json" file.

![image](https://user-images.githubusercontent.com/49699162/176550910-5664d06e-3876-4ad2-b570-da12e5f3e1f2.png)

**Comment by smashah** [comment]
@DaviZMelo unfortunately MD sessions are not portable in the same way as "legacy" sessions. Now session.data.json is used as a placeholder just in case we are able to crack MD session portability. There has been some research done with regards to MD portability but it's still not determined if it is even possible.

It's annoying because I was really proud with the work done on backing up session data in s3 now it's pretty useless. The _IGNORE_ folders are "locked" to the machine/machine ID/container so it's not portable in the same way as session data. Also, _IGNORE_ folders are constantly changing/updating.

Track #2338 for updates.

Thanks

**Comment by smashah** [comment]
Please track https://github.com/open-wa/wa-automate-nodejs/issues/2866
