### ISSUE TITLE
I did what you said but the result did not change.

### ISSUE THREAD

**Issue by yasin1913** [open-wa/wa-automate-nodejs#2841]
I did what you said but the result did not change.
Could it be because of the proxy service I'm using?

The reason we use proxy is we run more than 10 clients on a single server, because we think we may be banned by whatsapp

Proxy Service: brightdata
Proxy Network Type: ISP

<img width="418" alt="Ekran Resmi 2022-07-20 10 37 44" src="https://user-images.githubusercontent.com/5730607/179924665-3b55e512-da4a-4375-8fce-0fc7a8d0a0b2.png">

_Originally posted by @yasin1913 in https://github.com/open-wa/wa-automate-nodejs/issues/2792#issuecomment-1189956852_

**Comment by smashah** [comment]
if that's the reason you're using a proxy then i think you don't have anything to worry about. VPNs are normal so IP cannot be a ban vector IMO.

Best thing to do is to make sure your VPS running these 10 sessions is using a VPN service which is popular with a lot of other people (e.g mullvad has a wiregaurd/openvpn setup you can use) instead of proxying every session via the browser through a highly questionable service like brightdata (previously luminati).

In all my years doing this, IP wasn't identified as a singular main reason in the event of a ban.
