### ISSUE TITLE
This is a fork of Sulla project

### ISSUE THREAD

**Issue by robertsLando** [open-wa/wa-automate-nodejs#291]
You should add to your readme that this project is also based on [sulla](https://github.com/danielcardeenas/sulla/tree/master/src/lib/wapi) as it started from a fork of it

It's just for fairness

**Comment by smashah** [comment]
As far as I'm concerned this project is so far removed from the original sulla project that the distinction is completely redundant. All code at the fork point is mostly non-functional - no work (functionality or otherwise, yet) since then has been transferred from there to here. Changes have mainly streamed from here to there with extra code-maintainability improvements. If you'd like to move your node-red integration to `open-wa` let me know. Thanks.
