### ISSUE TITLE
TypeError: groupId.replace is not a function

### ISSUE THREAD

**Issue by dmzoneill** [open-wa/wa-automate-nodejs#2910]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

```
    client.onParticipantsChanged(async event => {
      console.log(event);
    });
```

```
/home/dave/src/whatsbot/node_modules/@open-wa/wa-automate/dist/api/Client.js:1024
            const funcName = "onParticipantsChanged_" + groupId.replace('_', "").replace('_', "");
                                                                ^

TypeError: groupId.replace is not a function
    at Client.<anonymous> (/home/dave/src/whatsbot/node_modules/@open-wa/wa-automate/dist/api/Client.js:1024:65)
    at Generator.next (<anonymous>)
    at /home/dave/src/whatsbot/node_modules/@open-wa/wa-automate/dist/api/Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dave/src/whatsbot/node_modules/@open-wa/wa-automate/dist/api/Client.js:23:12)
    at Client.onParticipantsChanged (/home/dave/src/whatsbot/node_modules/@open-wa/wa-automate/dist/api/Client.js:1023:16)
    at ChuckBot.start (/home/dave/src/whatsbot/chuckbot.js:67:12)
    at /home/dave/src/whatsbot/chuckbot.js:43:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

- check groupid is string or not null.
- shouldn't fail on startup

### Steps To Reproduce

```
    client.onParticipantsChanged(async event => {
      console.log(event);
    });
```

### DEBUG INFO

```markdown
wa.create({
      sessionId: "chuck",
      multiDevice: true,
      authTimeout: 60,
      blockCrashLogs: true,
      disableSpins: true,
      headless: true,
      hostNotificationLang: 'IE_EN',
      logConsole: true,
      logConsoleErrors: true,
      popup: false,
      useChrome: true,
      qrTimeout: 0,
      logging: [
        {
          "type": "console"
        }
      ]
    }).then(client => start(client));
```
```


### Environment

```markdown
- OS: debian 
- Node: v18.7.0
- npm: 8.19.2
```

**Comment by smashah** [comment]
Hi @dmzoneill 

[`onParticipantsChanged`](https://openwa.dev/docs/api/classes/api_Client.Client#onparticipantschanged) is a special event function because it takes two parameters. The first is the group ID that you want to listen to and the second is the callback.

So in order to use it correctly you need to do something like this:

```js
    client.onParticipantsChanged("12345678912345@g.us",async event => {
      console.log(event);
    });
```

If you want to listen to all events from all groups you can use [`onGlobalParticipantsChanged `](https://openwa.dev/docs/api/classes/api_Client.Client#onglobalparticipantschanged)

If you have general questions like this you can ask in the discord for more assistance from the community (click the discord badge in the readme)
