### ISSUE TITLE
[Feature Request] - Forward Poll (With metadata)

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-nodejs#3006]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Current Behavior

Hi there!, first of all , same as usual, love you guys - youre the best! :)
Wanted to know if you can add a feature to forward an existing poll to some other group/chat
I'll emphasize that i'm not talking about copying and recreating a poll, i mean to pass it on with all the data - user's choices
to some other place. hopefully it can be done.
If so and it goes by reference, we can pass a poll between a few places and see all the users that voted , from diffrent groups.
Like a global poll haha

let me know what you think, and if i should put this feature request somewhere else...
Thanks alot! all the best, and have a good one!

### Steps To Reproduce

Should look like:
`api.forwardPoll(poll_id, chat_id)`

### DEBUG INFO

```markdown
<>
```

### Environment

```markdown
<>
```

### Anything else?

❤️

**Comment by fire17** [comment]
sorry for the formatting, next time ill just use the clean new issue
https://github.com/open-wa/wa-automate-nodejs/issues/new

**Comment by smashah** [comment]
I don't see how this is possible with whatsapp as is since you're not allowed to forward polls to other groups. Even if you could do that it wouldn't sync poll results between groups.

Nice concept though. Maybe it can be replicated in some other way? Maybe use a third party polling service then periodically allow people to check on the poll in the chat via some sort of API request that generates a poll results image/message?

Or just collate poll results from different groups in a mega poll which can be periodically checked?

**Comment by smashah** [comment]
Maybe the sendPoll command should be able to take an array of GroupChatIDs to send the poll to?

IDK, hard to see how to implement this without a concrete use case.

Unfortunately i'll have to close this. Feel free to discuss this concept with the community on discord (click the discord badge in the readme).
