### ISSUE TITLE
Concern about the license checking method

### ISSUE THREAD

**Issue by awangn6600** [open-wa/wa-automate-nodejs#323]
Hello, good work with the project! I really loved this project, because the official way to use whatsapp bot is very expensive and i can't afford it for just for experimenting.

I have a concern about how the license checking works, in this line
https://github.com/open-wa/wa-automate-nodejs/blob/d5b69d3c4a63db70a75396b5f31cf8be001bb4a6/src/controllers/initializer.ts#L181-L183
It is basically "eval"-ing any code that come from your remote server retrieved from here
https://github.com/open-wa/wa-automate-nodejs/blob/3cdfafd3120af88d742edfcc6eb70d3547fe713d/package.json#L4
I didn't accuse you doing something wrong, it's just making me very uncomfortable, because I don't know what code runs on my server.
I know this is one of your way to enforce a license for enabling some features (i have read the pinned discussion), but I feel that this is just not right. Maybe you could create a private package for licensed user? Or maybe create two different package for the free and paid users? I don't know, I didn't really know the technical thing a lot.
For the meantime, I replaced the licenseCheckurl to localhost

Sorry for my bad English and keep up the good work!

**Comment by smashah** [comment]
@awangn6600  I can understand the paranoia, however, this only gets called if you have a licenseKey and I know you don't have one so there's nothing for you to worry about.

I don't have the time nor the interest to be snooping around on your Whatsapp web instances. However, if anyone else is concerned about me potentially siphoning data out of your Whatsapp web instance you can easily check by implementing this code:

```javascript
create(...).then(async client => {
await client.page.setRequestInterception(true);
client.page.on('request', interceptedRequest => console.log(interceptedRequest.url());
});
```

If from that you find any proof of me screwing around with your Whatsapp instances please feel free to tar and feather me - my reputation on this platform is ripe for destruction.

I would rather spend my time adding new features to this library instead of creating a parallel private one.

This is one of those cases where a little bit of knowledge is a bad thing. To recap:
1. The code only gets called if you have a license key. If you have no license key, no external requests are made by the library.
2. You have the tools to protect your Whatsapp web instances and I strongly encourage you to use them. Also, CORS.
3. I have every reason not to screw around with your instances.

For further info, the only thing the eval code does is it replaces the blank functions with proper functions.

**Comment by awangn6600** [comment]
thank you very much for the response and explanation, i really appreciate it. 

> This is one of those cases where a little bit of knowledge is a bad thing.
well i didn't think it's a bad thing, because i know i need to learn more, and learning is a process.

**Comment by smashah** [comment]
My apologies @awangn6600 that was out of line of me. Thanks for bringing it up. Please feel free to share any concerns in the future.
