### ISSUE TITLE
setGroupIconByUrl not working

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#345]
I checked, i got error:
"Failed to update group icon,Please try again later"

code:
await client.setGroupIconByUrl('972559661703-1587456110@g.us', 'https://res.cloudinary.com/picktags-com/image/upload/v1587297034/unnamed_3_vbkodw.png');

i also tried:

await client.setGroupIconByUrl('972559661703_1587456110@g.us', 'https://res.cloudinary.com/picktags-com/image/upload/v1587297034/unnamed_3_vbkodw.png');

**Comment by smashah** [comment]
WhatsApp does not accept pngs. Use a jpeg. @roysG

**Comment by smashah** [comment]
Also, the icon has to be very small otherwise it won't work.

**Comment by roysG** [comment]
I also tried now with this image:

https://res.cloudinary.com/picktags-com/image/upload/v1587464241/icon2_gdstwh.jpg

*Still not working*

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.74](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.73...1.8.74) (2020-04-21)

- Bump marked from 0.8.2 to 1.0.0 [`#342`](https://github.com/open-wa/wa-automate-nodejs/pull/342)
- Bump ts-node from 8.8.2 to 8.9.0 [`#343`](https://github.com/open-wa/wa-automate-nodejs/pull/343)
- Bump @types/node from 13.13.0 to 13.13.1 [`#344`](https://github.com/open-wa/wa-automate-nodejs/pull/344)
- Release 1.8.74 [`944a440`](https://github.com/open-wa/wa-automate-nodejs/commit/944a440a85db5f24ef6853661ad90b998a4205a8)
- Automatically convert images for `setGroupIcon` & `setGroupIconByUrl` #345 [`60179cf`](https://github.com/open-wa/wa-automate-nodejs/commit/60179cf011ec55374f385443023128b3b958a2ed)
- `getLastSeen` and `isChatOnline` now return false instead of error #347 [`c7c272d`](https://github.com/open-wa/wa-automate-nodejs/commit/c7c272d100d4a0988bdfb11dc7308a3e3ea2a374)

**Comment by smashah** [comment]
@roysG In the latest version 1.8.74, it now converts the image on to the correct size and format so your pngs and large jpegs should work now as long as [sharp](https://sharp.pixelplumbing.com/) works on your system.

Tested to be working:

```javascript 

//large jpeg
 await client.setGroupIconByUrl("447777777777-1579189596@g.us", "https://upload.wikimedia.org/wikipedia/commons/1/16/HDRI_Sample_Scene_Balls_%28JPEG-HDR%29.jpg");

//and with png
 await client.setGroupIconByUrl("447777777777-1579189596@g.us", "https://res.cloudinary.com/picktags-com/image/upload/v1587297034/unnamed_3_vbkodw.png'");
```

Let me know if this worked for you. Thanks

**Comment by roysG** [comment]
AWSOME!

**Comment by smashah** [comment]
@roysG there are no plans for a UI layer on this repo.
