### ISSUE TITLE
Re-sync contacts after a new contact is added

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#392]
Hi, is it possible to resync the `Contact` store after a new contact is added to the phone? Right now you have to open the WhatsApp app on the phone to resync, do you think we can avoid that and trigger it from the API?

**Comment by smashah** [comment]
@tinyCoder32 try v1.9.7 

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#synccontacts

**Comment by tinyCoder32** [comment]
Thank you for the quick response, I can query the added contact now. However, I have another question please, `Store.Contact.sync()` does not update the chat list with the added contact until I open WhatsApp app, it immediately changes from showing the phone number only, to the added contact name. Is there a way to update the interface of WhatsApp Web after adding the contact?

I appreciate your kind efforts.

**Comment by smashah** [comment]
@tinyCoder32 Just checked the source for WhatsApp. The only other syncing is to 'refresh' the details of specific contact and unless someone submits a PR, there are no plans for a UI layer on this project as I don't have the capacity to maintain it. Since this is an interaction between Whatsapp mobile and the phone itself I don't see how this process can be triggered from solely Whatsapp Web. I'll close this for now until I find something new.
