### ISSUE TITLE
can׳t send video or image

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#503]
**Describe the bug**
I am using your code without any problem, but yesterday
I got errors when i tried to send image or video
https://ibb.co/KWH9HmM

I found similar issue:
https://github.com/open-wa/wa-automate-nodejs/issues/462

After i read the suggested solution i added the parameter:

browserRevision:"737027"

After that, the images sent ok, but when i sent video, i got error similar to this bug:
https://github.com/open-wa/wa-automate-nodejs/issues/11#issuecomment-557886099

And i can׳t figure out how to solve it.

**Steps to Reproduce**
1. send image and see the errors in the console 
And then you will get errors:
https://ibb.co/KWH9HmM

**create() code**
const client = await create({
            autoRefresh:true, //default to true
            qrRefreshS:25,
            executablePath: process.platform === 'linux' ? "/usr/bin/google-chrome" : "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            headless: process.platform === 'linux' ? true : false,
        });
```

**Expected behavior**
the images and videos to send ok

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
┌─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                     │
├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2021.4'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.56'                                                                    │
│   BROWSER_VERSION   │                                                             'Chrome/83.0.4103.61'                                                             │
└─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Host (please complete the following information):**
 - OS: [e.g. iOS]
 - Macbook pro


**More info:**
Important to mention this,
When I tried to open new tab of web whatsapp (in the same window browser), the manual upload image and video was ok.

**Comment by roysG** [comment]
The problem is still happening also in the new version "1.9.57"

**Comment by dogcalas** [comment]
First, when you set **browserRevision:"737027"** , what you are doing is specifying the "Chromium"  (not Chrome) build that you want to use. With Chromium you can't send videos.
 
The last chrome version 83.XXXX, still given those CORS problems, so, for now you have to downgrade your Chrome to version 81.XXXX. 

Remove your actual Chrome, and download from [here](https://www.slimjet.com/chrome/google-chrome-old-version.php) the last working version (81.0.4044.92)

**Comment by roysG** [comment]
Thanks I will check it

**Comment by jesusvalverde** [comment]
**Describe the bug**

Not able to send a File or a image


**Steps to Reproduce**

const wa = require('@open-wa/wa-automate');
const axios = require('axios');

wa.create('test',{cacheEnabled:false}).then(client => start(client));

async function start(client) {
  await client.sendText('506xxxxxx@c.us', 'Hello! la prueba llega');

  await client.sendFileFromUrl('506xxxxxxc.us', 'https://test.io/wp-content/uploads/2019/02/testIO-logo-rgb-2.png', 'test.png', 'Caption');

  file= await getBase64('https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/09/12/11/naturo-monkey-selfie.jpg');
  await client.sendImage('506xxxxxx@c.us',file , 'test.png', 'Caption');

  file= await getBase64('https://londres.cervantes.es/imagenes/prueba_de_nivel.pdf');
  await client.sendFile('506xxxxxx@c.us', file , 'file', 'Caption');

}

async function getBase64(url) {
 const res = await axios
      .get(url, {
        responseType: 'arraybuffer'
      });
    return `data:${res.headers['content-type']};base64,${Buffer.from(res.data, 'binary').toString('base64')}`
}





**Expected behavior**

Sent text work work no problem , but image or files not.


**DEBUG INFO**
node test.ts
       
                                                                                    
✓ Initializing WA
│     WA_VERSION      │                                                                  '2.2021.4'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.57'                                                                    │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'                                                          
✓ Authenticated
✓ WAPI Reinjected
✓ Client is ready
✓ Passed Integrity Test```


**Additional context**
The same code is working over a equal server but with a 1.9.31 version  [not upgraded since] but If I do try just to instal this version It do not work.

**Comment by roysG** [comment]
Work!

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.59](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.58...1.9.59) (2020-05-31)

- Release 1.9.59 [`4dc208d`](https://github.com/open-wa/wa-automate-nodejs/commit/4dc208daa7e68ca8b229a114f1e5dc5ad1780034)
- fix: remove DNT override from intercepted requests #503 [`9babb3d`](https://github.com/open-wa/wa-automate-nodejs/commit/9babb3d168ad27a08cc8f27a28b4045d228ebccb)

**Comment by smashah** [comment]
@roysG @dogcalas @jesusvalverde can you try the latest version and let me know if it worked for you. Thanks.

**Comment by jesusvalverde** [comment]
Working on my side....

Check sendFileFromUrl
Check sendFilecheck 
Check sendImage 

Fine form me.. Great @smashah
