### ISSUE TITLE
Feature: Add optional sessionId to api path

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#547]
The middleware doesn't take into account node processes with multiple sessions

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.72](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.71...1.9.72) (2020-06-14)

- Release 1.9.72 [`d682060`](https://github.com/open-wa/wa-automate-nodejs/commit/d68206014f830da7c6ea643b1500417d427e55bc)
- feature: BREAKING sessionId can now be set as path on middleware. Change `middleware` to `middleware()` or `middleware(true)` please check docs and demo #547 [`8e53dcb`](https://github.com/open-wa/wa-automate-nodejs/commit/8e53dcbb286d3546d3844f351a67581c99700acb)

**Comment by smashah** [comment]
In both examples, the session Id is `host`

```javascript
 ...
  app.use(client.middleware());
 ...
```

The request URL: `localhost:8082/sendText`


```javascript
 ...
  app.use(client.middleware(true));
 ...
```

The request URL: `localhost:8082/host/sendText`

**Comment by smashah** [comment]
@MgArreaza13

**Comment by MgArreaza13** [comment]
@smashah 
good morning brother I hope you are very well, first I want to congratulate you for a great job. I have several implementation questions and I hope you can help me. I need to make an api where I can connect several sessions, therefore I need to do it in an orderly way. I explain to you I have several routes as I told you before, I have routes to start the session, I have routes to see contacts, I have routes to see groups, example

builder() {
this.router.get ('/ retrieve-all-messages /: chatId', homeController.retrieveAllMessages);
this.router.get ('/ new-message /: contactId /: message', homeController.newMessage);
this.router.get ('/ get-connections-state', homeController.getConnectionState);
this.router.get ('/ validate-number /: number', homeController.validateNumber);
this.router.get ('/ check-status-device', homeController.checkStatusDevices);
this.router.get ('/ get-battery-level', homeController.getBatteryLevel);
this.router.get ('/ get-host-devices', homeController.getHostDevice);
this.router.get ('/ contacts', homeController.contacts);
this.router.get ('/ groups', homeController.groups);
this.router.get ('/ unread', homeController.unread);
this.router.get ('/ test', homeController.test);
}

Now, at the session start which is test, I would like to return to the front client a token or something that allows me to identify the session and attach it to each request so that I do not have to make each request to create the 'client' intact but only Check if the session is active or not, and process the request. Why? good because currently all the methods that I use from your library are instantiated from the client object that the correct create method returns to me? so what does that mean? that for me to be able to obtain the contacts I execute the create method and then I pass it to that action so this always generates a delay in the responses from my server. so I wish I could optimize that process. Do you have any idea how I can do something like that?

/ auth return token
/ get-message /: token

for example something like this, where you don't need to create every time
get-message () {
token = req.params.token
if (token === valid) {
res.send (token.getContacts)
}
}
as well

venom.create ('test'). then (async (client: any) => {
client.sendText (req.params.contactId, req.params.message);
res.status (200) .send (message sent: $ {req.params.message});
});

because the venom.create ('') part I'm always doing

**Comment by MgArreaza13** [comment]
@smashah  
Can I solve this problem with your library? could you help me?

**Comment by smashah** [comment]
@MgArreaza13 have you considered using https://github.com/joaomirandasa/whats2api ? It does pretty much everything you need
