### ISSUE TITLE
Unable to get lastseen and online status of chat, returns false

### ISSUE THREAD

**Issue by Manjit2003** [open-wa/wa-automate-nodejs#594]
Hey guys please help me as this is quite urgent..
**I am unable to check if chat is online or not**

I am using this code : 

`WAPI.isChatOnline('91XXXXXXXXXX@c.us').then(data=>{console.log(data)})`

but it always returns false..

somebody please help me as this is quite urgent..

@smashah i have great hopes with you , hope you might help..

**Comment by smashah** [comment]
This isn't an issue with the library. WhatsApp web doesn't detect a chat being 'online' instantly. The best thing to do is call that `isChatOnline` a few times when you expect the chat to be online with an interval of about 1 second. That will give the web instance the chance to receive the 'message' that the chat is online.

Or you can use `client.onChatState(x=>console.log(x))` and listen out for the 'available' state 

Check it out here: https://github.com/open-wa/wa-automate-nodejs/issues/578#issuecomment-651148272

**Comment by smashah** [comment]
@Manjit2003 also if you're unable to see the last seen or online status of a chat it may be due to privacy settings. Some people don't want you to see their last online time and online status. Also if the host phone has these privacy settings on then open-wa will not be able to see anyone's last seen time and online status.
