### ISSUE TITLE
Remove Client.ts from /dist folder

### ISSUE THREAD

**Issue by sandro-salles** [open-wa/wa-automate-nodejs#676]
**Describe the bug**
While moving my setup to use typescript, since i'm using strict checking/validation, whenever i try to build/watch the project it throws lots of errors because it seems that **api/Client.ts** is getting packed to dist folder too (i think it probably shouldn't, right?). 

**Steps to Reproduce**
1. Add the project as a dependency (yarn add @open-wa/wa-automate)
2. Try to build or watch my own project (yarn build/watch)
4. See errors

**Expected behavior**
Client.ts should not be there, only compiled (**Client.js**) version and the **Client.d.ts** file

**Screenshots**
![Screen Shot 2020-07-25 at 11 57 46](https://user-images.githubusercontent.com/1104617/88459763-1c047500-ce6e-11ea-9b82-f26e4243e297.png)

![Screen Shot 2020-07-25 at 11 55 46](https://user-images.githubusercontent.com/1104617/88459746-fd05e300-ce6d-11ea-9684-642fdf93a219.png)

For now i'm manually removing the .ts file and it works fine!

Regards

**Comment by smashah** [comment]
@sandro-salles it is meant to be there but maybe I can rename it without breaking the functionality that requires it to be there. I'll look into it

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.105](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.104...1.9.105) (2020-07-25)

- Release 1.9.105 [`64759fc`](https://github.com/open-wa/wa-automate-nodejs/commit/64759fce5bc823106face336bba6a5bc732ecb41)
- puppeteer proxy confirmed to be working #670 [`495618f`](https://github.com/open-wa/wa-automate-nodejs/commit/495618fcaaa9f17a3660f511db8a02e021f671b6)
- fix: remove client.ts from dist to prevent ts errors #676 [`5374569`](https://github.com/open-wa/wa-automate-nodejs/commit/5374569a58416657761ff9d65228ed31a7cb2355)
- chore: revert debug info to be logged before process instead of waiting for launch time ms [`7cdf7ee`](https://github.com/open-wa/wa-automate-nodejs/commit/7cdf7eed9890ce6195fdcd0408de1547ba97e03c)
- chore: Update required node version to &gt;&gt; 12.18.3 [required for proxy to work] [`4f6a2a7`](https://github.com/open-wa/wa-automate-nodejs/commit/4f6a2a72ce8cfaa6075ecc81e31f2e093ee39059)
- chore: remove express from devdeps [`4affd91`](https://github.com/open-wa/wa-automate-nodejs/commit/4affd914e6ec75340a81c65395dc75bf7d25182a)

**Comment by sandro-salles** [comment]
Fixed now! Thanks man 👍
