### ISSUE TITLE
Websockets instead of Puppeteer?

### ISSUE THREAD

**Issue by ramonck** [open-wa/wa-automate-nodejs#723]
Hi @smashah,

I don't know if you have ever seen this websocket approach instead of the puppeteer approach? Do you even think it's viable for the features you have to be working with websockets?

https://github.com/sigalor/whatsapp-web-reveng
https://github.com/adiwajshing/Baileys

**Comment by smashah** [comment]
Hey @ramonck Yes I've seen and tried (on a small scale) those libraries and considered the move, however, decided not to for the following reasons:

1. @adiwajshing is doing a great job as is, I've no intention on stepping on toes in this space, as I know myself how annoying and frustrating that is.
2. My personal expertise is on developing and uncovering features through the 'browser' and, if need be, I can optionally whisper to the WebSocket to get things done (for example buttons and text stories) - effectively I get 2 'attack' vectors in one using this method. Why should I figure out the ws messages if I can force WA Web to do it for me?
3. This method gives me access and visibility to upcoming features - I have a custom browser.ts that unlocks upcoming features (kinda boring most times as the features are usually blocked due to the mobile app not being beta).
4. Protection - wa-automate works on top of a browser, not editing WA's code or hijacking web sockets. The difference may seem trivial but it may be the one single reason this project won't get DMCAd (https://news.ycombinator.com/item?id=22209892). wa-automate does not circumvent any of WA's measures of security. It merely automates existing browser features.
5. I haven't tried to send videos on Baileys, but the process using a browser-based approach is fairly simple - just make sure the browser has access to FFmpeg and it does the rest (re: making the thumbnail, making it playable etc.)
6. The 2 major benefits of a ws approach are better load times and more efficient memory consumption. Both are being currently addressed. I managed to get a session loaded in about 3.5 seconds once. Memory consumption will be addressed with #713 - there are plans to further improve memory consumption down the road.
7. If both are addressed, the ws approach will still have better memory consumption as it doesn't need a browser. I think this memory hit is worth it for all the other advantages.

Hope that answers your question @ramonck 

Fun fact: Translating @sigalor's method of decryption to NodeJS was the reason I forked [sulla](https://github.com/danielcardeenas/sulla) in the first place.

**Comment by ramonck** [comment]
Sometimes I think about it and the browser is the biggest issue always both in memory consumption and in some weird bugs like I have seen in the past, that's why I wanted to share it with you. I mean instead of stepping on each other toes I think more about combining great stuff together and get better "results" for you both I don't see any other library out there with as many features as this one and the browser is the "hassle" I cannot trust to use this library in anything because of the browser situation "it crashes, excessive memory consumption, etc." I mean you know about it all.
But you have put some much effort into it implementing such great features I wished I could combine the features from this library into a web sockets based implementation like from @adiwajshing. That's why I asked you this and you seem like the most active person on this type of library so I just basically wanted to let you know and give you some ideas if you didn't have them in mind.
Have a great rest of the weekend.
