### ISSUE TITLE
ReferenceError: getQrPng is not defined

### ISSUE THREAD

**Issue by kodmanyagha** [open-wa/wa-automate-nodejs#961]
(node:1416647) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (/automated/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:171:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ExecutionContext.evaluate (/automated/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:1416647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1416647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
V3 does not work with edited WAPI's. Also, fill in the issue template in the future.

**Comment by raphox** [comment]
I would like to make some customizations and contributions to the project. How can I change and build the project without generating this problem?

**Comment by smashah** [comment]
@raphox if you've got ideas and how to implement them, bring them up in a new issue and I will implement it while adding you as a contributor on the commit. Thanks

**Comment by raphox** [comment]
@smashah If I understand correctly, this repository no longer represents 100% of the library's functionality. As far as I could see, most of the features are implemented in encrypted form in the file https://github.com/open-wa/wa-automate-nodejs/blob/master/patches.json. We also don't have access to the original source of that file. Right?

I understand that you have personal reasons for doing so. But that way the repository is no longer open source. Do you intend to change your mind at some point?

**Comment by smashah** [comment]
@raphox the goal of this library is to allow as many people as possible to reliably automate their accounts, not to mindlessly adhere to an idealistic notion of what "open source" is meant to be.

The reason the patches are unreadable are because other libraries were copying code without any attribution while at the same time insulting this library. Not very "open source" is it? It also protects the code from being broken.

I'm not sure if you are aware but all Instagram libraries got DMCAd last year and removed from GitHub. In order to prevent that from happening, I, at first, did not allow the ability to send messages to unknown numbers to stop script kiddies and assholes from spamming people. When the feature was eventually implemented (in #254), the license of this project was also changed (H+DNH) which is not an "open source" license.

If you require further information as to why this library isn't as "open" as you'd like, please contact the code thieves, Mark Zuckerdouche, anybody else making money off this library without sharing their code, the script kiddies, spammers, fascists and scammers.

As I mentioned previously, I am more than happy to (and have done so many times in the past) add people as contributors on my commits when some technical ideas are shared.

**Comment by raphox** [comment]
Ok @smashah. I understand your position. And I thank you for still keeping part of the library open. I know you could be allocating everything from the API and other internal components, and I think it is part of the retribution to the other contributors. I was just curious and had no intention of demanding.

Congratulations on the tool and your job of maintaining it. :clap:
