### ISSUE TITLE
 Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by Amunamkhan** [open-wa/wa-automate-nodejs#995]
Hi, 
When  I am trying to wa-automate-nodejs demo.Iam getting below erorr.

EV Cannot read property 'readFile' of undefined customer-support STARTUP
----------
Error Cannot read property 'readFile' of undefined

**Comment by smashah** [comment]
@Amunamkhan 

I'm pretty sure this is related to https://github.com/puppeteer/puppeteer/issues/6548

which is fixed in the latest version of puppeteer (#993)

I will merge this PR but it wont be live till the next release.

For now, I would suggest making sure you're using nodejs version 12.18.3+ with this library as mentioned in the README.

**Comment by smashah** [comment]
@Amunamkhan puppeteer has been updated on the latest version. Please update to 3.0.8 and try again
 Report back if still happening.

**Comment by Amunamkhan** [comment]
Yes, it's working fine now, this is issue was coming due to the **Lower node version.**
